### PR TITLE
Added missing partition create/update properties

### PR DESCRIPTION
**Pull request by andy-maier**
For details, see the commit message.

### CODE REVIEW

**Review by anilak11 — COMMENTED** [review]
I found all the properties other than **boot-removable-media-type** for the create partition Action, or Am I missing that ?

**Review by EdGue42 — APPROVED** [review]
Quickly looked over it, seems okay.
(just wondering: no corresponding unit test updates?)

**Comment by andy-maier** [comment]
Edwin: The zhmccli project has nearly no testcases. That is something to address separately.

**Review by vkathir82 — APPROVED** [review]

**Comment by andy-maier** [comment]
Re-running the test "fixed" the test issue in https://github.com/zhmcclient/zhmccli/actions/runs/6416258751/job/17419652868 - since this no longer occurred and in addition cannot possible have to do anything with this PR, I am merging the PR.

**Pull request merged**
