### PR TITLE
Make it easier to execute the test cases

### PR DESCRIPTION
**Pull request by mhartmay**
Remove the requirement that ``zhmccli`` must be installed to run the tests.

### CODE REVIEW

**Comment by mhartmay** [comment]
Seems like current PyYAML version doesn't work with Python 3.4.*.

```
Collecting PyYAML (from python-coveralls)

Downloading https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz (268kB)

    100% |████████████████████████████████| 276kB 5.3MB/s 

PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8

The command "$PIP_CMD install python-coveralls" failed and exited with 1 during .

Your build has been stopped.
```

See https://travis-ci.org/zhmcclient/zhmccli/jobs/633665235?utm_medium=notification&utm_source=github_status for details.

**Comment by andy-maier** [comment]
Marc, it is not clear to me why the command `python3 -m zhmccli` would make it easier to execute tests compared to the command `zhmc`. Also, the command name shown in help messages now changes from "zhmc" to "__main__.py". That is certainly unesirable.

**Comment by mhartmay** [comment]
The idea is that you don't have to install the Python package for running the tests. Secondly, it's a common idiom to have something like that (see https://docs.python.org/3/library/__main__.html for details) - it allows to start the zhmccli by using the command `python3 -m zhmccli`.

We could also call `python3 zhmccli` within the zhmccli repository, if there wouldn't be the following problem (see https://stackoverflow.com/questions/16981921/relative-imports-in-python-3):
```
$ pwd
/home/mhartmay/git/zhmccli
$ python3 zhmccli
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "zhmccli/__main__.py", line 22, in <module>
    from zhmccli.zhmccli import cli
  File "zhmccli/zhmccli.py", line 30, in <module>
    from ._helper import CmdContext, GENERAL_OPTIONS_METAVAR, REPL_HISTORY_FILE, \
ImportError: attempted relative import with no known parent package
```

**Comment by andy-maier** [comment]
Marc, `make install` installs the package in an editable fashion, you can edit the files and test with `make test` or with any manually executed `zhmc` command, so what you ask for ("you don't have to install the Python package for running the tests") already exists.

On the approach for scripts described in https://docs.python.org/3/library/__main__.html : Sure, that is the built-in approach for turning a Python module into a script. There are other approaches though, and we are using the approach to declare an entry point in the setup.py file, which causes the `zhmc` script to be generated by setuptools upon installation (both editable and normal). That has the advantage that it always works regardless of whether the Python environment is a virtualenv, a venv, a user Python or a system Python, and also regardless of the OS. The approach with `__main__` is not a replacement for that (e.g. there is no shebang that works in all OSs). So if we introduce the approach with `__main__`, we now have two ways to invoke the functionality.

I have thought about your idea of changing the semantics of `make install` to be an installation that does not depend on the repo, but then we would need something else that performs the editable install, and pip does not handle the switching between editable and non-editable installs very well. If you need a non-editable install, it should be done with pip from Pypi. I believe that the need for a non-editable install from a particular branch of the repo is rare, and if you need it, `pip install .` will do exactly that.

So I'm closing this PR.

**Pull request closed without merging**
